(define-module (r0man guix home systems precision)
  #:use-module (gnu home services desktop)
  #:use-module (gnu home services gnupg)
  #:use-module (gnu home services shells)
  #:use-module (gnu home services sound)
  #:use-module (gnu home services)
  #:use-module (gnu home)
  #:use-module (gnu services)
  #:use-module (r0man guix home bash)
  #:use-module (r0man guix home btop)
  #:use-module (r0man guix home channels)
  #:use-module (r0man guix home clojure)
  #:use-module (r0man guix home common-lisp)
  #:use-module (r0man guix home eca)
  #:use-module (r0man guix home emacs)
  #:use-module (r0man guix home environment)
  #:use-module (r0man guix home fzf)
  #:use-module (r0man guix home git)
  #:use-module (r0man guix home gpg)
  #:use-module (r0man guix home guile)
  #:use-module (r0man guix home hyprland)
  #:use-module (r0man guix home i3status)
  #:use-module (r0man guix home kitty)
  #:use-module (r0man guix home librewolf)
  #:use-module (r0man guix home mbsync)
  #:use-module (r0man guix home msmtp)
  #:use-module (r0man guix home nix)
  #:use-module (r0man guix home packages)
  #:use-module (r0man guix home pm)
  #:use-module (r0man guix home rofi)
  #:use-module (r0man guix home shepherd)
  #:use-module (r0man guix home ssh)
  #:use-module (r0man guix home stumpwm)
  #:use-module (r0man guix home sway)
  #:use-module (r0man guix home waybar)
  #:use-module (r0man guix home wofi)
  #:use-module (r0man guix home xdg)
  #:use-module (r0man guix home x11))

(define services
  (append (make-home-bash-services)
          (make-home-channels-services)
          (make-home-pm-services)
          home-msmtp-services
          home-shepherd-services
          home-ssh-services
          home-xdg-services
          home-x11-services
          (list (service home-btop-service-type)
                (service home-clojure-service-type)
                (service home-common-lisp-service-type)
                (service home-dbus-service-type)
                (service home-eca-service-type)
                (service home-emacs-service-type)
                (service home-environment-service-type)
                (service home-fzf-service-type)
                (service home-git-service-type)
                (service home-gpg-agent-service-type home-gpg-gtk-configuration)
                (service home-guile-service-type)
                (service home-hyprland-service-type)
                (service home-i3status-service-type)
                (service home-kitty-service-type)
                (service home-librewolf-service-type)
                (service home-mbsync-service-type)
                (service home-nix-service-type)
                (service home-pipewire-service-type)
                (service home-rofi-service-type)
                (service home-stumpwm-service-type)
                (service home-sway-service-type)
                (service home-waybar-service-type)
                (service home-wofi-service-type))))

(define-public precision-home-environment
  (home-environment
   (packages packages)
   (services services)))

precision-home-environment
