;;; Copyright (C) 2026 Roman Scherer <roman@burningswell.com>
;;;
;;; Regenerate `tests/data/ghostty/golden-{minimal,heavy}.config`
;;; from the canonical schema.  Invoked by `make ghostty-golden`.
;;;
;;; The same configurations live in
;;; `tests/r0man/guix/home/ghostty.scm`.  Keep both in sync.

(use-modules (r0man guix home services ghostty)
             (ice-9 match))

(define top-srcdir
  (or (getenv "top_srcdir")
      (getenv "abs_top_srcdir")
      "."))

(define header
  "# Generated by 'make ghostty-golden' — DO NOT EDIT.\n")

(define minimal-config
  (home-ghostty-configuration
   (font-size 14)
   (theme "nord")))

(define heavy-config
  (home-ghostty-configuration
   (config-file '("themes/nord"))
   (font-family '("Iosevka" "Hack"))
   (font-size 14)
   (font-feature '("+liga" "ss01"))
   (cursor-style 'bar)
   (background-blur (background-blur (enabled? #t) (radius 30)))
   (background-image-position
    (background-image-position (vertical 'top) (horizontal 'left)))
   (palette '((0 . "000000") (1 . "ff0000")))
   (env '("" ("FOO" . "bar")))
   (keybind '(("ctrl+a" . "reset") "ctrl+b>c=close_tab"))
   (bell-features '(audio +attention))
   (extra-options '((some-future-key . "future-value")))
   (extra-content "# user override\nfont-thicken = true\n")))

(define (write-fixture name config)
  (let ((path (string-append top-srcdir "/tests/data/ghostty/" name)))
    (call-with-output-file path
      (lambda (port)
        (display header port)
        (display (home-ghostty-config->string config) port)))
    (format #t "Wrote ~a~%" path)))

(write-fixture "golden-minimal.config" minimal-config)
(write-fixture "golden-heavy.config"   heavy-config)
