# -*- mode: sh -*-

## GUIX

# XDG_DATA_DIRS often starts off empty, but an empty value is
# interpreted as this value. Loading a profile can set it, though,
# which effectively ignores the default value. We want it to instead
# add to the default, so we set it here to the default value.
if [ -z "$XDG_DATA_DIRS" ]; then
    export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
else
    export XDG_DATA_DIRS="$XDG_DATA_DIRS:/usr/local/share/:/usr/share/"
fi

# GUIX_PROFILE="$HOME/.guix-extra-profiles/r0man/profiles/emacs-native-comp"
# . "$GUIX_PROFILE/etc/profile"
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
for i in $GUIX_EXTRA_PROFILES/*; do
    profile=$i/$(basename "$i")
    if [ -f "$profile"/etc/profile ]; then
        GUIX_PROFILE="$profile"
        . "$GUIX_PROFILE"/etc/profile
        echo "Loaded Guix profile: $GUIX_PROFILE"
    fi
    unset profile
done

## GPG

# # export GPG_TTY="$(tty)"
# gpgconf --launch gpg-agent
# export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
# gpgconf --launch gpg-agent
# eval $(gpg-agent --daemon)

## SSH

for i in $(ls -1 ~/.ssh/*.pub ); do
    ssh-add ${i/.pub/}
done

## SOLARIZED

export SOLARIZED="dark"
if [ -e ~/.dotfiles/dircolors.ansi-$SOLARIZED ]; then
    eval `dircolors ~/.dotfiles/dircolors.ansi-$SOLARIZED`
fi

## COURSIER

export PATH="$PATH:/home/roman/.local/share/coursier/bin"

## FLUTTER

export CHROME_EXECUTABLE="chromium"
export PATH="$PATH:$HOME/local/flutter/bin"

## NPM
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$PATH:$NPM_PACKAGES/bin"

## KAFKA

KAFKA_HOME="$HOME/local/kafka"
if [ -d $KAFKA_HOME ]; then
    export KAFKA_HOME
    export PATH="$KAFKA_HOME/bin:$PATH"
fi

## NUBANK

export NU_COUNTRY="br"
export NU_HOME="$HOME/workspace/nu"

# NUCLI
export NUCLI_HOME="$NU_HOME/nucli"
export PATH="$PATH:$NUCLI_HOME"

# NUCLI.PY
export PATH="$PATH:$NU_HOME/nucli.py/bin"
export NUCLI_PY_FORMATTER_STYLE="bw"
# export NUCLI_PY_FULL=1

# PATH
export PATH="$PATH:$HOME/.dotfiles/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.node_modules/bin"
export PATH="$PATH:$HOME/bin:$PATH"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/local/sbin"
