#!/bin/sh
#
# ~/.xsession
#
# https://wiki.debian.org/Xsession
#

# Load Guix Home.
if [ -r ~/.profile ]; then . ~/.profile; fi

# Load ~/.xprofile
[[ -f ~/.xprofile ]] && . ~/.xprofile

# Start StumpWM
exec dbus-launch --sh-syntax --exit-with-session sbcl --load $HOME/.config/stumpwm/start
