(define-module (r0man guix home environments server)
  #:use-module (gnu home services desktop)
  #:use-module (gnu home services gnupg)
  #:use-module (gnu home services guix)
  #:use-module (gnu home services mail)
  #:use-module (gnu home services pm)
  #:use-module (gnu home services shells)
  #:use-module (gnu home services ssh)
  #:use-module (gnu home services)
  #:use-module (gnu home)
  #:use-module (gnu services)
  #:use-module (r0man guix home bash)
  #:use-module (r0man guix home services btop)
  #:use-module (r0man guix home channels)
  #:use-module (r0man guix home services claude-code)
  #:use-module (r0man guix home services clojure)
  #:use-module (r0man guix home services common-lisp)
  #:use-module (r0man guix home services eca)
  #:use-module (r0man guix home services emacs)
  #:use-module (r0man guix home services environment)
  #:use-module (r0man guix home services fzf)
  #:use-module (r0man guix home services git)
  #:use-module (r0man guix home gpg)
  #:use-module (r0man guix home services guile)
  #:use-module (r0man guix home services kitty)
  #:use-module (r0man guix home services mbsync)
  #:use-module (r0man guix home msmtp)
  #:use-module (r0man guix home services nix)
  #:use-module (r0man guix home packages)
  #:use-module (r0man guix home pm)
  #:use-module (r0man guix home ssh)
  #:use-module (r0man guix home tmux))

(define services
  (append (list (service home-bash-service-type
                         home-bash-default-configuration)
                (service home-btop-service-type)
                (service home-channels-service-type
                         home-channels-default-list)
                (service home-claude-code-service-type)
                (service home-clojure-service-type)
                (service home-common-lisp-service-type)
                (service home-dbus-service-type)
                (service home-eca-service-type)
                (service home-emacs-service-type)
                (service home-environment-service-type)
                (service home-fzf-service-type)
                (service home-git-service-type)
                (service home-kitty-service-type)
                (service home-gpg-agent-service-type
                         home-gpg-tty-configuration)
                (service home-guile-service-type)
                (service home-mbsync-service-type)
                (service home-msmtp-service-type
                         home-msmtp-default-configuration)
                (service home-nix-service-type)
                (service home-openssh-service-type
                         home-openssh-default-configuration)
                (service home-ssh-agent-service-type))
          home-tmux-services))

(define-public server-home-environment
  (home-environment
    (packages packages-base)
    (services services)))

server-home-environment
