# -*- mode: sh -*-

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# Load bash aliases.
[ -r ~/.bash_aliases ] && . ~/.bash_aliases

## AUTOJUMP
[ -r /etc/profile.d/autojump.bash ] && . /etc/profile.d/autojump.bash

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

#GUIX

GUIX_PROFILE="$HOME/.guix-profile"
if [ -d $GUIX_PROFILE ]; then
    . "$GUIX_PROFILE/etc/profile"
fi

## BASH

# Preserve Bash History in Multiple Terminal Windows
# https://www.baeldung.com/linux/preserve-history-multiple-windows
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

## GPG
export GPG_TTY="$(tty)"

## EAT (Emulate A Terminal)

# Source eat's bash integration if available
if [ -n "$EAT_SHELL_INTEGRATION_DIR" ]; then
    source "$EAT_SHELL_INTEGRATION_DIR/bash"
fi

# Reset custom shell prompt when logged in with Tramp.
if [ "$TERM" == "dumb" ]; then
    PS1="[\u@\h \w]$ "
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
