# -*- mode: sh -*-

## ANDROID
ANDROID_HOME="$HOME/Android/Sdk"
if [ -d "$ANDROID_HOME" ]; then
    export ANDROID_HOME
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
fi

## BURNING SWELL

if [ -d "$HOME/workspace/burningswell" ]; then

    export BURNINGSWELL_HOME="$HOME/workspace/burningswell"

    if [ -e "$HOME/workspace/burningswell/deploy/burningswell/config/google/cloud/service-accounts/development.json" ]; then
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/workspace/burningswell/deploy/burningswell/config/google/cloud/service-accounts/development.json
    fi

fi

## CONFLUENT

CONFLUENT_HOME="$HOME/local/confluent-7.3.0"
if [ -d "$CONFLUENT_HOME" ]; then
    export CONFLUENT_HOME
    export PATH="$PATH:$CONFLUENT_HOME/bin"
fi

## Leiningen
export LEIN_JVM_OPTS="-Daether.dependencyCollector.impl=bf"

## Flatpak

if [ -d "$HOME/.local/share/flatpak/exports/share" ]; then
    export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/share/flatpak/exports/share"
fi
if [ -d "/var/lib/flatpak/exports/share" ]; then
    export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/flatpak/exports/share"
fi

## GUIX

# Setup GUIX on a foreign distro
# if [ -f /etc/profile.d/guix.sh ]; then
#     . /etc/profile.d/guix.sh
# fi

# # XDG_DATA_DIRS often starts off empty, but an empty value is
# # interpreted as this value. Loading a profile can set it, though,
# # which effectively ignores the default value. We want it to instead
# # add to the default, so we set it here to the default value.
# if [ -z "$XDG_DATA_DIRS" ]; then
#     export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
# else
#     export XDG_DATA_DIRS="$XDG_DATA_DIRS:/usr/local/share/:/usr/share/"
# fi

# # GUIX_PROFILE="$HOME/.guix-extra-profiles/r0man/profiles/emacs-native-comp"
# # . "$GUIX_PROFILE/etc/profile"
# GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
# for i in $GUIX_EXTRA_PROFILES/*; do
#     profile=$i/$(basename "$i")
#     if [ -f "$profile"/etc/profile ]; then
#         GUIX_PROFILE="$profile"
#         . "$GUIX_PROFILE"/etc/profile
#         echo "Loaded Guix profile: $GUIX_PROFILE"
#     fi
#     unset profile
# done

## GRAAL VM
GRAALVM_HOME="$HOME/graalvm/graalvm-community-openjdk-25.0.1+8.1"
if [ -e "$GRAALVM_HOME" ]; then
    export GRAALVM_HOME
else
    unset GRAALVM_HOME
fi

## NIX

NIX_PROFILE="/run/current-system/profile/etc/profile.d/nix.sh"
if [ -e "$NIX_PROFILE" ]; then
    source "$NIX_PROFILE"
fi

## GOOGLE CLOUD SDK

if [ -d "$HOME/local/google-cloud-sdk" ]; then
    export PATH="$PATH:~/local/google-cloud-sdk/bin"

    # The next line updates PATH for the Google Cloud SDK.
    if [ -f '~/local/google-cloud-sdk/path.bash.inc' ]; then . '~/local/google-cloud-sdk/path.bash.inc'; fi

    # The next line enables shell command completion for gcloud.
    if [ -f '~/local/google-cloud-sdk/completion.bash.inc' ]; then . '~/local/google-cloud-sdk/completion.bash.inc'; fi
fi

## SOLARIZED

if command -v vivid &>/dev/null; then
    export LS_COLORS="$(vivid -m 8-bit generate solarized-dark)"
fi

## TERMINAL COLOR SUPPORT

# Enable 24-bit true color support for kitty terminal
if [[ "$TERM" == "xterm-kitty" ]]; then
    export COLORTERM=truecolor
fi

## COURSIER

if [ -d "$HOME/.local/share/coursier/bin" ]; then
    export PATH="$PATH:$HOME/.local/share/coursier/bin"
fi

## CHROME
export CHROME_EXECUTABLE="chromium"

## FLUTTER

FLUTTER_ROOT="$HOME/local/flutter"
if [ -d "$FLUTTER_ROOT" ]; then
    export FLUTTER_ROOT
    export PATH="$PATH:$FLUTTER_ROOT/bin"
fi

## NPM
NPM_CONFIG_PREFIX="${HOME}/.npm/node_modules"
if [ -d "$NPM_CONFIG_PREFIX" ]; then
    export NPM_CONFIG_PREFIX
    export PATH="$PATH:$NPM_CONFIG_PREFIX/bin"
fi

## KAFKA

KAFKA_HOME="$HOME/local/kafka"
if [ -d $KAFKA_HOME ]; then
    export KAFKA_HOME
    export PATH="$KAFKA_HOME/bin:$PATH"
fi

## NUBANK

NU_HOME="$HOME/workspace/nu"
if [ -d "$NU_HOME" ]; then
    export NU_COUNTRY="br"
    export NU_HOME

    # NUCLI
    NUCLI_HOME="$NU_HOME/nucli"
    if [ -d "$NUCLI_HOME" ]; then
        export NUCLI_HOME
        export PATH="$PATH:$NUCLI_HOME"
    fi

    # NUCLI.PY
    if [ -d "$NU_HOME/nucli.py/bin" ]; then
        export PATH="$PATH:$NU_HOME/nucli.py/bin"
    fi
    if [ -d "$NU_HOME/mini-meta-repo/monocli/bin" ]; then
        export PATH="$NU_HOME/mini-meta-repo/monocli/bin:$PATH"
    fi
    export NUCLI_PY_FORMATTER_STYLE="bw"
fi

# PATH
[ -d "$HOME/.dotfiles/bin" ] && export PATH="$HOME/.dotfiles/bin:$PATH"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"
[ -d "$HOME/.node_modules/bin" ] && export PATH="$HOME/.node_modules/bin:$PATH"
[ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
[ -d "/usr/local/bin" ] && export PATH="$PATH:/usr/local/bin"
[ -d "/usr/local/sbin" ] && export PATH="$PATH:/usr/local/sbin"
