#!/usr/bin/env bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Load ~/.xprofile
[[ -f ~/.xprofile ]] && . ~/.xprofile

# Start StumpWM
exec sbcl --load $HOME/.config/stumpwm/start
