#!/usr/bin/env bash
#
# ~/.xprofile
#

# Load Bash profile
[ -f ~/.bash_profile ] && source ~/.bash_profile

# Load X Resources
[ -f ~/.Xresources ] && xrdb -all -load ~/.Xresources

# Load host specific X Resources
XRESOURCES_HOST=~/.Xresources.$(hostname)
[ -f $XRESOURCES_HOST ] && xrdb -merge $XRESOURCES_HOST

# Automatically select a display configuration based on connected devices.
if [ -x "$(command -v autorandr)" ]; then
    autorandr common
fi

# Make caps lock an additional control key.
setxkbmap -option "caps:ctrl_modifier"

# Kill the X server with Ctrl+Alt+Backspace.
setxkbmap -option "terminate:ctrl_alt_bksp"

# Swap the left window and the left alt keys (but not on Macbook).
if [ $(uname --machine) != "aarch64" ]; then
    setxkbmap -option "altwin:swap_lalt_lwin"
fi

# Remove Emoji hotkey, to make C-. work in Emacs.
# https://superuser.com/questions/1687342/what-is-my-x11-doing-with-ctrl-period-and-how-can-i-disable-it
gsettings set org.freedesktop.ibus.panel.emoji hotkey "@as []"

# Start picom, a compositor for X11.
picom --backend xrender &

# Dunst
killall dunst; dunst &

# Use a better mouse pointer
xsetroot -cursor_name left_ptr

# Start Music Player Daemon.
mpd &

# Start the screensaver
xscreensaver -no-splash &

# Start xbindkeys - a grabbing keys program for X.
xbindkeys

# Set wallpaper
feh --bg-scale ~/.local/share/wallpapers/stop-customizing-start-working.jpg

# Start XDG Desktop Portal (for Flatpak integration)
~/.guix-home/profile/libexec/xdg-desktop-portal-gtk &
sleep 1
~/.guix-home/profile/libexec/xdg-desktop-portal &

# Start Emacs.
emacs --bg-daemon &
