name: Test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Guix cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - name: Install Guix
        id: install-guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (list (channel
                    (name 'asahi
                    (url "https://github.com/asahi-guix/channel")
                    (branch "main")
                    (introduction
                     (make-channel-introduction
                      "3eeb493b037bea44f225c4314c5556aa25aff36c"
                      (openpgp-fingerprint
                       "D226 A339 D8DF 4481 5DDE  0CA0 3DDA 5252 7D2A C199"))))
                  (channel
                   (name 'guix)
                   (url "https://git.savannah.gnu.org/git/guix.git")
                   (branch "master")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
                  (channel
                   (name 'nonguix)
                   (url "https://gitlab.com/nonguix/nonguix")
                   (branch "master")
                   (introduction
                    (make-channel-introduction
                     "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
                     (openpgp-fingerprint
                      "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5"))))
                  (channel
                   (name 'r0man)
                   (url "https://github.com/r0man/guix-channel")
                   (branch "main")
                   (introduction
                    (make-channel-introduction
                     "8eb7a76af9b51b80f5c01f18639e6360833fc377"
                     (openpgp-fingerprint
                      "D226 A339 D8DF 4481 5DDE  0CA0 3DDA 5252 7D2A C199")))))
      - name: Guix home reconfigure m1
        run: guix home -L modules --dry-run reconfigure modules/r0man/guix/home/systems/m1.scm
      - name: Guix home reconfigure precision
        run: guix home -L modules --dry-run reconfigure modules/r0man/guix/home/systems/precision.scm
